Repository AY2122S1-CS2103T-T17-1/tp, pull requests merged in 2021-11, with the labels that each got.

#173 V1.4 Adding unit tests
  src/main/java/seedu/address/logic/parser/CheckCommandParser.java
  src/main/java/seedu/address/logic/parser/SetTablesCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/table/Table.java
  src/main/java/seedu/address/model/table/TableManager.java
  src/test/java/seedu/address/logic/commands/AddCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/AddEmployeeCommandTest.java
  src/test/java/seedu/address/logic/commands/AddSupplierCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/SetTablesCommandTest.java
  src/test/java/seedu/address/logic/parser/SetTablesCommandParserTest.java
  src/test/java/seedu/address/model/table/TableListTest.java
  src/test/java/seedu/address/model/table/TableManagerTest.java
  src/test/java/seedu/address/model/table/TableTest.java
Labels: priority.Medium

#175 PED issue fix
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SetTablesCommand.java
Labels: type.Bug, priority.Medium

#177 Fix PE-D issues
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddEmployeeCommand.java
  src/main/java/seedu/address/logic/commands/AddSupplierCommand.java
  src/main/java/seedu/address/logic/commands/EditEmployeeCommand.java
  src/main/java/seedu/address/model/person/customer/UniqueCustomerList.java
  src/main/java/seedu/address/model/person/employee/Salary.java
  src/main/java/seedu/address/model/person/employee/UniqueEmployeeList.java
  src/main/java/seedu/address/model/person/supplier/UniqueSupplierList.java
  src/test/java/seedu/address/model/person/employee/SalaryTest.java
Labels: type.Bug, priority.High, severity.Medium

#197 Add PPP and fix error messages
  docs/UserGuide.md
  docs/team/clementkfj.md
  src/main/java/seedu/address/model/person/customer/LoyaltyPoints.java
  src/main/java/seedu/address/model/person/employee/Leaves.java
  src/main/java/seedu/address/model/person/employee/Salary.java
  src/main/java/seedu/address/model/person/employee/Shift.java
Labels: type.Task, priority.High

#199 V1.4 test code quality
  src/main/java/seedu/address/model/table/Table.java
  src/test/java/seedu/address/logic/commands/CheckCommandTest.java
  src/test/java/seedu/address/logic/commands/SetTablesCommandTest.java
  src/test/java/seedu/address/model/reservation/CustomerContainsReservationPredicateTest.java
  src/test/java/seedu/address/model/reservation/ListContainsReservationPredicateTest.java
  src/test/java/seedu/address/model/reservation/ReservationListTest.java
  src/test/java/seedu/address/model/table/TableManagerTest.java
  src/test/java/seedu/address/model/table/TableTest.java
  src/test/java/seedu/address/testutil/TypicalTables.java
Labels: priority.Medium

#208 First draft of AddEmployee DG
  docs/DeveloperGuide.md
  docs/diagrams/AddEmployeeCommandActivityDiagram.puml
  docs/diagrams/AddEmployeeCommandClassDiagram.puml
  docs/diagrams/AddEmployeeCommandSequenceDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/AddEmployeeCommandActivityDiagram.png
  docs/images/AddEmployeeCommandClassDiagram.png
  docs/images/AddEmployeeCommandSequenceDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/CommitActivityDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/team/clementkfj.md
Labels: priority.High, severity.High

#217 Improve Diagrams
  docs/diagrams/AddEmployeeCommandClassDiagram.puml
  docs/diagrams/AddEmployeeCommandSequenceDiagram.puml
  docs/images/AddEmployeeCommandClassDiagram.png
  docs/images/AddEmployeeCommandSequenceDiagram.png
Labels: priority.Medium

#223 Improve Diagrams and format
  docs/DeveloperGuide.md
  docs/diagrams/AddEmployeeCommandActivityDiagram.puml
  docs/diagrams/AddEmployeeCommandSequenceDiagram.puml
  docs/images/AddEmployeeCommandActivityDiagram.png
  docs/images/AddEmployeeCommandSequenceDiagram.png
  docs/team/clementkfj.md
Labels: priority.High, severity.High

#222 V1.4 dg improvement
  docs/DeveloperGuide.md
  docs/team/hernpiblo.md
Labels: priority.Medium

#232 V1.4 uml fix
  docs/diagrams/SetTablesActivityDiagram.puml
  docs/diagrams/SetTablesSequenceDiagram.puml
  docs/images/SetTablesActivityDiagram.png
  docs/images/SetTablesSequenceDiagram.png
Labels: priority.Medium

#242 Add manual testing and use case
  docs/DeveloperGuide.md
Labels: priority.High, severity.High

#241 Update test cases for DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High

#250 V1.4b dg usecase testcase
  docs/DeveloperGuide.md
  docs/team/hernpiblo.md
Labels: priority.Medium
