Repository AY2122S1-CS2103T-T17-1/tp, pull requests merged in 2021-10, with the labels that each got.

#57 V1.2 check reservation
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/CheckCommand.java
  src/main/java/seedu/address/logic/commands/ReserveCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CheckCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/enums/EnumTypeOfCheck.java
  src/main/java/seedu/address/model/reservation/ListContainsReservationPredicate.java
  src/main/java/seedu/address/model/reservation/PersonContainsReservationPredicate.java
  src/main/java/seedu/address/model/reservation/Reservation.java
  src/main/java/seedu/address/storage/JsonAdaptedReservation.java
  src/test/java/seedu/address/logic/commands/CheckCommandTest.java
  src/test/java/seedu/address/logic/commands/ReserveCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CheckCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/ReserveCommandParserTest.java
  src/test/java/seedu/address/model/reservation/ListContainsReservationPredicateTest.java
  src/test/java/seedu/address/model/reservation/PersonContainsReservationPredicateTest.java
Labels: type.Task, type.Story, priority.High

#61 Add JUnit Tests
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Task, priority.High, severity.Medium

#85 Fix Person Removal in Ui
  src/main/java/seedu/address/logic/commands/PersonCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/CustomerCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/SupplierCard.java
  src/main/resources/view/EmployeeListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/test/java/seedu/address/logic/commands/PersonCommandTest.java
Labels: type.Task, priority.High, severity.High

#94 Add Tests & Fix bugs
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/employee/Shift.java
  src/main/java/seedu/address/storage/JsonAdaptedShift.java
  src/main/java/seedu/address/ui/EmployeeCard.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditEmployeeCommandTest.java
  src/test/java/seedu/address/logic/commands/EditEmployeeDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddEmployeeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditEmployeeCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedEmployeeTest.java
Labels: type.Enhancement, type.Bug, priority.High, severity.Medium

#99 Super search for employee
  src/main/java/seedu/address/logic/commands/FindEmployeeCommand.java
  src/main/java/seedu/address/logic/parser/FindEmployeeCommandParser.java
  src/main/java/seedu/address/model/person/employee/EmployeeClassContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/employee/EmployeeNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/EmployeeCard.java
  src/main/resources/view/DarkTheme.css
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EmployeeCommandTestUtil.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/employee/EmployeeClassContainsKeywordsPredicateTest.java
Labels: type.Enhancement, priority.High, severity.Medium
